[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$NodeDistributionPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$expectedNodeVersion = "v26.8.1"
$expectedNodeSha256 = "5CBA0EA928508C65DDADEFC0681D2FB6D95F1F3BEEA4428F04397631140EE8E5"
$expectedNodeLicenseSha256 = "ED34DD8E3F0A78DBAF00D0444CE8E285B015B765379C2E17880455F70370F8E9"
$expectedCliBanner = "markdownlint-cli2 v0.23.2 (markdownlint v0.41.1)"

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$resourcesPath = Join-Path $repositoryRoot "OneNoteMarkdownExporter\resources"
$nodePath = Join-Path $NodeDistributionPath "node.exe"
$npmPath = Join-Path $NodeDistributionPath "npm.cmd"
$nodeLicensePath = Join-Path $NodeDistributionPath "LICENSE"
$stagingPath = Join-Path ([System.IO.Path]::GetTempPath()) ("onenote-markdown-dependencies_" + [Guid]::NewGuid().ToString("N"))
$originalPath = $env:PATH

function Assert-FileExists([string]$Path, [string]$Description)
{
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf))
    {
        throw "$Description not found at: $Path"
    }
}

function Assert-ExitCode([int]$ExitCode, [string]$Operation)
{
    if ($ExitCode -ne 0)
    {
        throw "$Operation failed with exit code $ExitCode."
    }
}

Assert-FileExists $nodePath "Node.js executable"
Assert-FileExists $npmPath "npm executable"
Assert-FileExists $nodeLicensePath "Node.js license"
Assert-FileExists (Join-Path $resourcesPath "package.json") "Resource package manifest"
Assert-FileExists (Join-Path $resourcesPath "package-lock.json") "Resource package lock"
Assert-FileExists (Join-Path $resourcesPath ".markdownlint.json") "Bundled markdownlint configuration"

$nodeVersion = (& $nodePath --version).Trim()
Assert-ExitCode $LASTEXITCODE "Reading the Node.js version"
if ($nodeVersion -ne $expectedNodeVersion)
{
    throw "Expected Node.js $expectedNodeVersion, but found $nodeVersion."
}

$nodeHash = (Get-FileHash -LiteralPath $nodePath -Algorithm SHA256).Hash
if ($nodeHash -ne $expectedNodeSha256)
{
    throw "The Node.js executable does not match the pinned SHA-256 hash."
}

$nodeLicenseHash = (Get-FileHash -LiteralPath $nodeLicensePath -Algorithm SHA256).Hash
if ($nodeLicenseHash -ne $expectedNodeLicenseSha256)
{
    throw "The Node.js license does not match the pinned SHA-256 hash."
}

try
{
    New-Item -ItemType Directory -Path $stagingPath | Out-Null
    Copy-Item -LiteralPath (Join-Path $resourcesPath "package.json") -Destination $stagingPath
    Copy-Item -LiteralPath (Join-Path $resourcesPath "package-lock.json") -Destination $stagingPath

    $env:PATH = "$NodeDistributionPath;$originalPath"
    Push-Location $stagingPath
    try
    {
        & $npmPath install --package-lock-only --ignore-scripts --no-audit --no-fund
        Assert-ExitCode $LASTEXITCODE "Regenerating package-lock.json"

        & $npmPath ci --ignore-scripts --no-audit --no-fund
        Assert-ExitCode $LASTEXITCODE "Installing pinned build dependencies"

        $nccPath = Join-Path $stagingPath "node_modules\.bin\ncc.cmd"
        $cliEntryPath = Join-Path $stagingPath "node_modules\markdownlint-cli2\markdownlint-cli2-bin.mjs"
        & $nccPath build $cliEntryPath -o (Join-Path $stagingPath "dist") -m --license "THIRD-PARTY-NOTICES.generated.txt"
        Assert-ExitCode $LASTEXITCODE "Bundling markdownlint-cli2"
    }
    finally
    {
        Pop-Location
    }

    $bundlePath = Join-Path $stagingPath "dist\index.mjs"
    $generatedNoticesPath = Join-Path $stagingPath "dist\THIRD-PARTY-NOTICES.generated.txt"
    Assert-FileExists $bundlePath "Bundled markdownlint-cli2 runtime"
    Assert-FileExists $generatedNoticesPath "Generated npm notices"

    $cliOutput = (& $nodePath $bundlePath --version 2>&1 | Out-String).Trim()
    Assert-ExitCode $LASTEXITCODE "Starting the bundled markdownlint-cli2 runtime"
    if (-not $cliOutput.Contains($expectedCliBanner))
    {
        throw "The bundled CLI version did not match '$expectedCliBanner'."
    }

    $generatedNotices = [System.IO.File]::ReadAllText($generatedNoticesPath)
    if (-not $generatedNotices.Contains("markdownlint-cli2") -or -not $generatedNotices.Contains("markdownlint"))
    {
        throw "Generated notices do not contain the expected markdownlint packages."
    }

    $nodeLicense = [System.IO.File]::ReadAllText($nodeLicensePath)
    $combinedNotices = @"
THIRD-PARTY NOTICES

Node.js $expectedNodeVersion
https://nodejs.org/

$nodeLicense

Bundled npm packages
Generated by @vercel/ncc from the dependencies locked in resources/package-lock.json.

$generatedNotices
"@

    Copy-Item -LiteralPath $nodePath -Destination (Join-Path $resourcesPath "node.exe") -Force
    Copy-Item -LiteralPath $bundlePath -Destination (Join-Path $resourcesPath "markdownlint-cli2.mjs") -Force
    Copy-Item -LiteralPath (Join-Path $stagingPath "package-lock.json") -Destination (Join-Path $resourcesPath "package-lock.json") -Force
    [System.IO.File]::WriteAllText(
        (Join-Path $resourcesPath "THIRD-PARTY-NOTICES.txt"),
        $combinedNotices,
        [System.Text.UTF8Encoding]::new($false))

    Write-Host "Updated Node.js $expectedNodeVersion and $expectedCliBanner."
    Write-Host "Run 'dotnet test OneNoteMarkdownExporter.slnx' to validate the committed runtime."
}
finally
{
    $env:PATH = $originalPath
    if (Test-Path -LiteralPath $stagingPath)
    {
        Remove-Item -LiteralPath $stagingPath -Recurse -Force
    }
}
